<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInite073ae0df0d9f36cade2b41e7c2a8a15
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInite073ae0df0d9f36cade2b41e7c2a8a15', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInite073ae0df0d9f36cade2b41e7c2a8a15', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInite073ae0df0d9f36cade2b41e7c2a8a15::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
