<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite073ae0df0d9f36cade2b41e7c2a8a15
{
    public static $prefixLengthsPsr4 = array (
        'T' =>
        array (
            'Taman\\Astrologer\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Taman\\Astrologer\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite073ae0df0d9f36cade2b41e7c2a8a15::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite073ae0df0d9f36cade2b41e7c2a8a15::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite073ae0df0d9f36cade2b41e7c2a8a15::$classMap;

        }, null, ClassLoader::class);
    }
}
